wallpaper {
    monitor = DP-1
    path = /home/diego/Pictures/Wallpapers/austrian_village.png
    fit_mode = cover
}

splash = false

# preload = /home/diego/Pictures/Wallpapers/austrian_village.png
# wallpaper = , /home/diego/Pictures/Wallpapers/austrian_village.png
